The Extremely Rad Everything Tengoku Pack
chrislo27/RhythmHeavenRemixEditor2 pull request #105
Opened 2017-04-07 23:25 UTC by GuardedLolz

### Prerequisites
* [X] I have read and understood the [contribution guidelines](CONTRIBUTING.md)
* [X] This pull request follows the code style of the project
* [X] I have tested this feature thoroughly WITH THE USE of the load-all-sounds starter
  * [Link to a video of proof of testing]()

### Changes Proposed in this Pull Request
**BLUE BIRDS**
Add Japanese and Spanish SFX.
**BON ODORI**
Completely revamped. (thankfully)
**FIREWORKS**
Is now segmented and the fireworks get their real names. The Rhythm Rockets are Base BPM at the moment, because the music decided to interfere.
**HEAD SPINNER**
The Bracelety of Rhythm Heaven finally comes to the Remix Editor.
**NIGHT WALK**
Added wot and different jump layouts.
**POLYRHYTHM**
Added clear sound.
**POWER CALIGRAPHY**
Added. Though I wonder why it wasn't here in the first place.
**QUIZ SHOW**
Added a version of the correct answer sound without the fanfare.
**RAP MEN**
Added and fixed patterns. It is now officially bigger than Ringside.
**SPACE DANCE**
Added Cosmic Dance.
**TAP TRIAL**
Added Remix 7 version.
**TOSS BOYS**
Segmented super start sounds for Ao-kun and Aka-chan. Added Aka-chan's unused super.

...

2017-04-07 23:38 UTC, chrislo27 commented
You didn't change games.json. Do not check off the "I have tested this feature thoroughly" checkbox until you have done so!

2017-04-07 23:47 UTC, chrislo27 commented
Is it really that hard to test? `fanClubEn` doesn't exist (there's a `fanClub` folder though).

2017-04-07 23:51 UTC, chrislo27 commented
Also, do you have a Discord account? Contacting me in (more) real time is easier on the Rhythm Heaven server (we have a rhre2 channel). The invite link is in the sidebar of https://www.reddit.com/r/rhythmheaven/.

2017-04-07 23:57 UTC, chrislo27 commented
Deprecations missing:
```
bonOdori/dondon1, bonOdori/dondon2, bonOdori/pan, bonOdori/panpan1, bonOdori/panpan2, nightWalk_jump, tossBoys/superRed, tossBoys/superBlue
```

2017-04-08 00:57 UTC, chrislo27 requested changes

2017-04-08 00:57 UTC, chrislo27 commented on core/assets/data/games.json
> +  "lockstep64",
Please remove (converted to a module for v2.10.2).

2017-04-08 00:57 UTC, chrislo27 commented on core/assets/data/games.json
> +  "tramAndPauline",
(data.json) doesn't exist yet.

2017-04-08 01:06 UTC, chrislo27 commented
Overall, I am incredibly happy with this pull request. It's clear you put a lot of time and effort into this, and it shows! :+1:

2017-04-08 01:12 UTC, chrislo27 requested changes

2017-04-08 01:12 UTC, chrislo27 commented on core/assets/sounds/cues/rapMen/data.json
> +      "id": "rapMen/orenosei1",
Accidental duplicate `orenosei` cues? (1, 2, 3)

2017-04-08 01:17 UTC, chrislo27 commented
Also, I think Cosmic Dance needs a swung and pose/turn right cue. Not too sure though.

2017-04-08 02:34 UTC, GuardedLolz commented
I think Cosmic Dance poses are just the original Space Dance pose, but on the offbeat.

2017-04-08 02:35 UTC, GuardedLolz commented on core/assets/sounds/cues/rapMen/data.json
> +      "id": "rapMen/orenosei1",
Fixed.

2017-04-08 02:36 UTC, GuardedLolz commented on core/assets/data/games.json
> +  "lockstep64",
What's a module?

2017-04-08 02:50 UTC, chrislo27 commented
I think the "turn" part is shifted forward by an sixth of a beat (like your other cosmic patterns). Better to have it for consistency than not at all, I suppose.

2017-04-08 02:55 UTC, GuardedLolz commented
Apart from being on the offbeat, the cosmic pose cue has nothing that sets it apart from the normal cue.

2017-04-08 03:05 UTC, chrislo27 commented
Fair enough. Please fix the rest of the things I pointed out in the review and I might try to get a snapshot out today for testing.

2017-04-08 03:05 UTC, GuardedLolz commented
I did.

2017-04-08 03:08 UTC, chrislo27 commented
Bleh, GH only *sometimes* updates commits in real-time. I'll check them now, sorry!

2017-04-08 03:09 UTC, GuardedLolz commented
I just forgot to sync my commit,

2017-04-08 03:11 UTC, merged

2017-04-08 03:13 UTC, GuardedLolz commented
The very next thing I am going to do after this is add more foreign sounds.