Add Freeze Frame
chrislo27/RhythmHeavenRemixEditor2 pull request #118
Opened 2017-04-13 15:33 UTC by Armodillomatt12

### Prerequisites
* [x] I have read and understood the [contribution guidelines](CONTRIBUTING.md)
* [x] This pull request follows the code style of the project
* [x] I have tested this feature thoroughly WITH THE USE of the load-all-sounds starter
  * [Link to a video of proof of testing](https://www.youtube.com/watch?v=7HolFz9raQw)

**Issues Fixed:** [Any issues fixed by this pull request]

### Changes Proposed in this Pull Request
* added freeze frame to `games.json` and added cues for it as well.

...
P.S. i had to make a new fork because the one i had is outdated. sorry if i'm being annoying

2017-04-13 15:50 UTC, GuardedLolz commented
You deleted Animal Acrobat, Tram and Pauline, Airboarder, and Space Soccer.

2017-04-13 15:51 UTC, GuardedLolz requested changes
DO NOT remove games.

2017-04-13 15:52 UTC, GuardedLolz commented
Now you just have to wait.

2017-04-13 15:52 UTC, Armodillomatt12 commented
sorry...

2017-04-13 15:55 UTC, Armodillomatt12 commented
i accidentally put `games.json` to the `freezeFrame` folder. i didn't delete `games.json` from data.

2017-04-14 01:58 UTC, GuardedLolz commented
Also, I think the yellow cars should be 0.5 beats. That would save us the trouble of using tracks.

2017-04-14 03:10 UTC, GuardedLolz requested changes
The yellow cars need to be 0.5 beats.

2017-04-14 03:22 UTC, chrislo27 requested changes

2017-04-14 03:22 UTC, chrislo27 commented on core/assets/sounds/cues/freezeFrame/data.json
> +  "track": 0
Formatting

2017-04-14 03:22 UTC, chrislo27 commented on core/assets/sounds/cues/freezeFrame/data.json
> +  "track": 0
Formatting

2017-04-14 03:22 UTC, chrislo27 commented on core/assets/sounds/cues/freezeFrame/data.json
> +      "duration": 1.0,
Should be 0.5 beats

2017-04-14 03:22 UTC, chrislo27 commented on core/assets/sounds/cues/freezeFrame/data.json
> +	"track": 1
Keep it one-dimensional (assuming you're also making it 0.5 beats as mentioned)

2017-04-14 10:44 UTC, Armodillomatt12 commented on core/assets/sounds/cues/freezeFrame/data.json
> +  "track": 0
what do you by formatting?

2017-04-14 10:55 UTC, Armodillomatt12 commented
here the link of the cues you wanted me to change for the small cars. https://www.youtube.com/watch?v=8bIm5Y9rzxE

2017-04-14 12:27 UTC, GuardedLolz commented on core/assets/sounds/cues/freezeFrame/data.json
> +  "track": 0
He means you should put spaces there.

2017-04-14 13:37 UTC, Armodillomatt12 commented on core/assets/sounds/cues/freezeFrame/data.json
> +  "track": 0
beginning signal 1 and 2?

2017-04-14 13:42 UTC, Armodillomatt12 commented on core/assets/sounds/cues/freezeFrame/data.json
> +  "track": 0
knowing that we don't use spaces.

2017-04-14 16:11 UTC, merged