Save the Swing (Add swing to Glee Club and Shrimp Shuffle and add Japanese versions of those games), also mole warnings.
chrislo27/RhythmHeavenRemixEditor2 pull request #125
Opened 2017-04-19 23:23 UTC by GuardedLolz

### Prerequisites
* [X] I have read and understood the [contribution guidelines](CONTRIBUTING.md)
* [X] This pull request follows the code style of the project
* [X] I have tested this feature thoroughly WITH THE USE of the load-all-sounds starter
  * I will upload a video if necessary.

### Changes Proposed in this Pull Request
See above.

...

2017-04-19 23:28 UTC, chrislo27 requested changes
Misleading title? I don't see any swing in Glee Club nor do I think it's necessary if present.

2017-04-19 23:28 UTC, chrislo27 commented on core/assets/sounds/cues/gleeClubEn/data.json
> +      "fileExtension": "wav"
Convert to ogg vorbis please

2017-04-19 23:33 UTC, GuardedLolz commented
toGe...therNow!

2017-04-21 01:34 UTC, GuardedLolz commented
Dude. The video. It exists for a reason.

2017-04-21 03:48 UTC, chrislo27 commented
Please avoid being rude. I don't stalk this pull request day and night, and every time you make a PR initially you never provide a video.

2017-04-21 03:49 UTC, merged