add chameleon
chrislo27/RhythmHeavenRemixEditor2 pull request #129
Opened 2017-04-26 17:53 UTC by Armodillomatt12

### Prerequisites
* [x] I have read and understood the [contribution guidelines](CONTRIBUTING.md)
* [x] This pull request follows the code style of the project
* [x] I have tested this feature thoroughly WITH THE USE of the load-all-sounds starter
  * [Link to a video of proof of testing](https://www.youtube.com/watch?v=VxsE56tpJ_o)

**Issues Fixed:** [Any issues fixed by this pull request]

### Changes Proposed in this Pull Request
* added cues for chameleon
* added chameleon to games.json

...

2017-04-26 21:07 UTC, GuardedLolz requested changes
The bug buzzing (not the prepare sounds) should loop.

2017-04-26 21:08 UTC, GuardedLolz requested changes
It's "Ja", not "Jp". Also, no folder for the Japanese Count-Ins.

2017-04-26 21:52 UTC, GuardedLolz commented
Still, Ja, not Jp. Also, deprecations.

2017-04-26 21:58 UTC, Armodillomatt12 commented
i don't know how to change names or delete folders... i need help

2017-04-27 14:55 UTC, GuardedLolz commented
And I mean a proper loop. Intro sound included. And stretchable.

2017-04-29 00:59 UTC, chrislo27 requested changes
Test things **thoroughly** next time.

2017-04-29 00:59 UTC, chrislo27 commented on core/assets/sounds/cues/countInJp/data.json
> +{
Remove the countInJp folder

2017-04-29 00:59 UTC, chrislo27 commented on core/assets/sounds/cues/countInEn/data.json
> +        "countinen_4BeatCountInCowbell"
You clearly didn't test this with deprecations. This is not a valid deprecated ID.

2017-04-29 00:59 UTC, chrislo27 commented on core/assets/sounds/cues/countInEn/data.json
> +      "id": "countInEn/cowbell",
Why do none of these have deprecations?

2017-05-01 23:21 UTC, closed without merging

2017-05-01 23:21 UTC, Armodillomatt12 commented on core/assets/sounds/cues/countInJp/data.json
> +{
i don't know how to