Add the minigame "LumBEARjack"
chrislo27/RhythmHeavenRemixEditor2 pull request #45
Opened 2016-12-20 11:53 UTC by Pengu12345

Also , we need to make a better Icon.

2016-12-20 11:56 UTC, Pengu12345 commented
The minigame database seems to have errors , but I don't know why...  If someone would check or fix the error , it could be nice ^^

2016-12-20 18:31 UTC, chrislo27 requested changes
Please change the title of this pull request to accurately describe what changes you made. Overall, a very sloppy pull request that does not follow the file format naming style + the json has syntax errors everywhere.

2016-12-20 18:31 UTC, chrislo27 commented on core/assets/data/games.json
> +  "LumBearJack"
Use `camelCase`.

2016-12-20 18:31 UTC, chrislo27 commented on core/assets/sounds/cues/LumBearJack/data.json
> +   "id" : "lumBearJack/Nyah"
Syntax errors everywhere. Run this json file through a validator and fix all of them.

2016-12-20 18:31 UTC, chrislo27 commented on core/assets/sounds/cues/LumBearJack/data.json
> +       },
Formatting is completely off.

2016-12-20 18:46 UTC, chrislo27 requested changes
More JSON style errors

2016-12-20 18:46 UTC, chrislo27 commented on core/assets/sounds/cues/LumBearJack/data.json
> +   "id" : "lumBearJack/Nyah"
Again, IDs use `camelCase`. This should just be `nyah`.

2016-12-20 18:46 UTC, chrislo27 commented on core/assets/sounds/cues/LumBearJack/data.json
> +   "name": "Nyah"
Names are also generally lower case.

2016-12-20 18:46 UTC, chrislo27 commented on core/assets/sounds/cues/LumBearJack/data.json
> +   "name": "Pose"
Lower case names.

2016-12-20 18:46 UTC, chrislo27 commented on core/assets/sounds/cues/LumBearJack/data.json
> +   "name": "Single hit"
Lower case names.

2016-12-20 18:46 UTC, chrislo27 commented on core/assets/sounds/cues/LumBearJack/data.json
> +   "name": "Double 1"
Lower case names.

2016-12-20 18:46 UTC, chrislo27 commented on core/assets/sounds/cues/LumBearJack/data.json
> +   "name": "Double 2"
Lower case names.

2016-12-20 18:46 UTC, chrislo27 commented on core/assets/sounds/cues/LumBearJack/data.json
> +   "name": "Big Pose"
Lower case names.

2016-12-20 18:46 UTC, chrislo27 commented on core/assets/sounds/cues/LumBearJack/data.json
> +   "name": "Big 1"
Lower case names. Use `big log 1`.

2016-12-20 18:46 UTC, chrislo27 commented on core/assets/sounds/cues/LumBearJack/data.json
> +   "name": "Big 2"
Lower case names. Use `big log 2`.

2016-12-20 18:46 UTC, chrislo27 commented on core/assets/sounds/cues/LumBearJack/data.json
> +	],
Formatting.

2016-12-20 18:46 UTC, chrislo27 commented on core/assets/sounds/cues/LumBearJack/data.json
> +   "name": "Big 3"
Lower case names.

2016-12-20 18:46 UTC, chrislo27 commented on core/assets/sounds/cues/LumBearJack/data.json
> +   "name": "Big Hit"
Lower case names.

2016-12-20 18:46 UTC, chrislo27 commented on core/assets/sounds/cues/LumBearJack/data.json
> +		{
Formatting.

2016-12-20 18:46 UTC, chrislo27 commented on core/assets/sounds/cues/LumBearJack/data.json
> +	"name": "Double"
Lower case names.

2016-12-20 18:46 UTC, chrislo27 commented on core/assets/sounds/cues/LumBearJack/data.json
> +  }
Newline at end of file.

2016-12-20 18:46 UTC, chrislo27 commented on core/assets/sounds/cues/LumBearJack/data.json
> +	"id": "lumBearJack_Big"
Use `camelCase` for IDs.

2016-12-20 18:46 UTC, chrislo27 commented on core/assets/sounds/cues/LumBearJack/data.json
> +        "id": "lumBearJack/Nyah",
Use `camelCase` for IDs.

2016-12-20 18:46 UTC, chrislo27 commented on core/assets/sounds/cues/LumBearJack/data.json
> +        "id": "lumBearJack/Nyah",
Use `camelCase` for IDs.

2016-12-20 18:46 UTC, chrislo27 commented on core/assets/sounds/cues/LumBearJack/data.json
> +	    "id": "lumBearJack/Pose",
Use `camelCase` for IDs.

2016-12-20 18:46 UTC, chrislo27 commented on core/assets/sounds/cues/LumBearJack/data.json
> +	    "id": "lumBearJack/SingleHit",
Use `camelCase` for IDs.

2016-12-20 18:46 UTC, chrislo27 commented on core/assets/sounds/cues/LumBearJack/data.json
> +	"id": "lumBearJack_Double"
Use `camelCase` for IDs.

2016-12-20 18:46 UTC, chrislo27 commented on core/assets/sounds/cues/LumBearJack/data.json
> +	    "id": "lumBearJack/Pose",
Use `camelCase` for IDs.

2016-12-20 18:46 UTC, chrislo27 commented on core/assets/sounds/cues/LumBearJack/data.json
> +	    "id": "lumBearJack/Double1",
Use `camelCase` for IDs.

2016-12-20 18:46 UTC, chrislo27 commented on core/assets/sounds/cues/LumBearJack/data.json
> +	    "id": "lumBearJack/Double2"
Use `camelCase` for IDs.

2016-12-20 18:46 UTC, chrislo27 commented on core/assets/sounds/cues/LumBearJack/data.json
> +   "id" : "lumBearJack/Big1"
IDs use `camelCase`.

2016-12-20 18:46 UTC, chrislo27 commented on core/assets/sounds/cues/LumBearJack/data.json
> +   "id" : "lumBearJack/BigPose"
IDs use `camelCase`.

2016-12-20 18:46 UTC, chrislo27 commented on core/assets/sounds/cues/LumBearJack/data.json
> +   "id" : "lumBearJack/Double2"
IDs use `camelCase`.

2016-12-20 18:46 UTC, chrislo27 commented on core/assets/sounds/cues/LumBearJack/data.json
> +   "id" : "lumBearJack/Double1"
IDs use `camelCase`.

2016-12-20 18:46 UTC, chrislo27 commented on core/assets/sounds/cues/LumBearJack/data.json
> +   "id" : "lumBearJack/SingleHit"
IDs use `camelCase`.

2016-12-20 18:46 UTC, chrislo27 commented on core/assets/sounds/cues/LumBearJack/data.json
> +   "id" : "lumBearJack/Pose"
IDs use `camelCase`.

2016-12-20 19:17 UTC, Pengu12345 commented
I see , sorry :c 

I will try to fix theses problems ^^'

2016-12-21 11:19 UTC, Pengu12345 commented
I tried to fix the problems.
If there are any more problems , please tell me ^^

2016-12-22 19:11 UTC, chrislo27 requested changes
You didn't change the camelCase requirements on the folder name nor the sound file names. There's still formatting errors.

2016-12-22 19:11 UTC, chrislo27 commented on core/assets/sounds/cues/LumBearJack/data.json
> +     "name": "pingle hit",
pingle

2016-12-22 19:11 UTC, chrislo27 commented on core/assets/sounds/cues/LumBearJack/data.json
> +"patterns" : [
Formatting

2016-12-22 19:11 UTC, chrislo27 commented on core/assets/sounds/cues/LumBearJack/data.json
> +},
Formatting

2016-12-22 19:11 UTC, chrislo27 commented on core/assets/sounds/cues/LumBearJack/data.json
> +{
Formatting

2016-12-22 19:11 UTC, chrislo27 commented on core/assets/sounds/cues/LumBearJack/data.json
> +	         ]
Formatting

2017-01-06 01:31 UTC, chrislo27 commented
#46 covers this.

2017-01-06 01:31 UTC, closed without merging