Save Base BPM!
chrislo27/RhythmHeavenRemixEditor2 pull request #97
Opened 2017-03-28 14:59 UTC by GuardedLolz

### Prerequisites
* [X] I have read and understood the [contribution guidelines](CONTRIBUTING.md)
* [X] This pull request follows the code style of the project
* [X] I have tested this feature thoroughly WITH THE USE of the load-all-sounds starter
  * [Link to a video of proof of testing]()

### Changes Proposed in this Pull Request
* Add pitch-changing versions of the Blue Birds cues
* Add Spanish and Japanese Blue Birds

...

2017-03-28 15:04 UTC, chrislo27 reviewed
Looks fine with a quick skim. Will wait for the video.

2017-03-28 15:04 UTC, chrislo27 commented on core/assets/data/games.json
>    "marchingOrdersEn",
Retain alphabetical order.

2017-03-28 15:04 UTC, chrislo27 commented on core/assets/data/games.json
>    "spaceDanceEn",
Retain alphabetical order

2017-03-28 15:16 UTC, GuardedLolz commented
Then for the sake of consistency, I will change the orders like this:
Japanese, then English, then Spanish.

2017-03-28 16:15 UTC, chrislo27 commented
Use alphabetical order.

2017-03-28 20:19 UTC, GuardedLolz commented
Sorry about my bad mood. It's just the inconvenient situation.

2017-03-28 20:22 UTC, GuardedLolz commented
I'm sorry. I don't mean to be rude.

2017-03-29 03:24 UTC, chrislo27 commented
Nah, you weren't rude. I have a tendency to be straightforward when reviewing stuff (Discord4J taught me how) :P

2017-03-29 22:54 UTC, chrislo27 requested changes
It is obvious you do not test your changes (otherwise these syntax errors would be gone!). Because you are deprecating some IDs, please test saving all the deprecated IDs and then loading it with your version for it to make sure it properly converts.

Syntax errors: http://i.imgur.com/EwllgZv.png

2017-03-29 22:54 UTC, chrislo27 commented on core/assets/sounds/cues/spaceDanceJa/data.json
> +      "deprecatedIDs": ["spaceDance_pupupupunch1"]
Missing comma. It's evident that you didn't test the PR with all sounds loaded because this error would've been caught.

2017-03-29 22:54 UTC, chrislo27 commented on core/assets/sounds/cues/spaceDanceJa/data.json
> +      "deprecatedIDs": ["spaceDance_turnright2"]
Missing comma.

2017-03-29 22:54 UTC, chrislo27 commented on core/assets/sounds/cues/spaceDanceJa/data.json
> +      "deprecatedIDs": ["spaceDance_letssitdown2"]
Missing comma.

2017-03-29 22:54 UTC, chrislo27 commented on core/assets/sounds/cues/spaceDanceJa/data.json
> +      "deprecatedIDs": ["spaceDance_pupupupunch2"]
Missing comma.

2017-03-29 23:13 UTC, chrislo27 commented
I ran a script to check deprecations: all good.

2017-03-30 21:53 UTC, GuardedLolz commented
I am going to close the pull request here and do a bigger one someday.

2017-03-30 21:53 UTC, closed without merging

2017-03-31 03:05 UTC, chrislo27 commented
:thinking: It would be fine if you had just fixed those four syntax errors (+ tested it).